// src/mockData/promotions.ts

export const mockPromotions = [
  {
    id: 1,
    eventName: 'Summer Savings',
    promoName: 'Buy One Get One Free',
    promoType: 'BOGO',
    startDate: '2025-07-01',
    endDate: '2025-07-15',
    offerSummary: 'Buy one lawn chair, get one free',
    buyCondition: 'Buy 1 Lawn Chair',
    getOutcome: 'Get 1 Free',
    storeCount: 45,
    hotsheetType: 'Seasonal',
    promoId: 'SUMMER-BOGO-2025',
    hasError: false,
    errorDetails: null,
  },
  {
    id: 2,
    eventName: 'Back to School',
    promoName: '20% Off School Supplies',
    promoType: 'Discount',
    startDate: '2025-08-01',
    endDate: '2025-08-31',
    offerSummary: '20% off select items',
    buyCondition: 'Any School Supplies',
    getOutcome: '20% Off',
    storeCount: 112,
    hotsheetType: 'Core',
    promoId: 'BTS-20OFF-2025',
    hasError: true,
    errorDetails: {
      title: 'Missing Required Field',
      message: 'The "Target Audience" field is mandatory for "Discount" type promotions.',
      code: 'PROMO-VALIDATION-005',
      solution: 'Edit the promotion and fill in the "Target Audience" field.'
    }
  },
  {
    id: 3,
    eventName: 'Holiday Decor Sale',
    promoName: '50% Off All Ornaments',
    promoType: 'Clearance',
    startDate: '2025-11-20',
    endDate: '2025-12-24',
    offerSummary: 'Half price on all holiday ornaments',
    buyCondition: 'Any Ornament',
    getOutcome: '50% Off',
    storeCount: 80,
    hotsheetType: 'Holiday',
    promoId: 'HOLIDAY-ORN-2025',
    hasError: false,
    errorDetails: null,
  },
  {
    id: 4,
    eventName: 'Spring Cleaning Event',
    promoName: 'Buy 2 Get 1 Cleaning Supplies',
    promoType: 'BOGO',
    startDate: '2026-03-01',
    endDate: '2026-03-15',
    offerSummary: 'Buy two cleaning products, get one free',
    buyCondition: '2 Cleaning Products',
    getOutcome: '1 Free',
    storeCount: 60,
    hotsheetType: 'Seasonal',
    promoId: 'SPRING-CLEAN-2026',
    hasError: false,
    errorDetails: null,
  },
  {
    id: 5,
    eventName: 'Electronics Blowout',
    promoName: '10% Off Laptops',
    promoType: 'Discount',
    startDate: '2025-09-01',
    endDate: '2025-09-10',
    offerSummary: '10% discount on all laptops',
    buyCondition: 'Any Laptop',
    getOutcome: '10% Off',
    storeCount: 150,
    hotsheetType: 'Tech',
    promoId: 'ELEC-LAPTOP-2025',
    hasError: true,
    errorDetails: {
      title: 'Approval Pending',
      message: 'This promotion is awaiting final marketing approval. It cannot go live until approved.',
      code: 'APPROVAL-001',
      solution: 'Contact marketing department for approval status.'
    }
  },
  {
    id: 6,
    eventName: 'Winter Apparel Sale',
    promoName: 'Up to 30% Off Jackets',
    promoType: 'Percentage Off',
    startDate: '2025-10-15',
    endDate: '2025-11-30',
    offerSummary: 'Savings on winter jackets and coats',
    buyCondition: 'Select Jackets',
    getOutcome: 'Up to 30% Off',
    storeCount: 90,
    hotsheetType: 'Seasonal',
    promoId: 'WINTER-JACKET-2025',
    hasError: false,
    errorDetails: null,
  },
  {
    id: 7,
    eventName: 'Garden Essentials',
    promoName: 'Buy 3 Get 1 Seeds',
    promoType: 'BOGO',
    startDate: '2026-04-01',
    endDate: '2026-04-15',
    offerSummary: 'Buy 3 packs of seeds, get 1 free',
    buyCondition: '3 Seed Packs',
    getOutcome: '1 Seed Pack Free',
    storeCount: 50,
    hotsheetType: 'Seasonal',
    promoId: 'GARDEN-SEED-2026',
    hasError: false,
    errorDetails: null,
  },
  {
    id: 8,
    eventName: 'Home Improvement',
    promoName: '15% Off Flooring',
    promoType: 'Discount',
    startDate: '2025-07-20',
    endDate: '2025-08-05',
    offerSummary: '15% discount on all types of flooring',
    buyCondition: 'Any Flooring',
    getOutcome: '15% Off',
    storeCount: 130,
    hotsheetType: 'Home',
    promoId: 'HOME-FLOOR-2025',
    hasError: true,
    errorDetails: {
      title: 'Price Mismatch',
      message: 'The promotional price entered does not match the product\'s current base price in inventory system.',
      code: 'DATA-SYNC-003',
      solution: 'Verify product pricing in inventory system and adjust promotion details.'
    }
  },
  {
    id: 9,
    eventName: 'Kitchen Upgrade',
    promoName: '25% Off Cookware Sets',
    promoType: 'Discount',
    startDate: '2025-09-15',
    endDate: '2025-09-30',
    offerSummary: '25% discount on selected cookware sets',
    buyCondition: 'Select Cookware Sets',
    getOutcome: '25% Off',
    storeCount: 100,
    hotsheetType: 'Home',
    promoId: 'KITCHEN-COOK-2025',
    hasError: false,
    errorDetails: null,
  },
  {
    id: 10,
    eventName: 'Fall Harvest Festival',
    promoName: 'Buy 1 Get 1 Fall Decor',
    promoType: 'BOGO',
    startDate: '2025-09-25',
    endDate: '2025-10-10',
    offerSummary: 'Buy one fall decoration, get one free',
    buyCondition: '1 Fall Decor Item',
    getOutcome: '1 Free',
    storeCount: 70,
    hotsheetType: 'Seasonal',
    promoId: 'FALL-DECOR-2025',
    hasError: false,
    errorDetails: null,
  },
  {
    id: 11,
    eventName: 'Fitness First',
    promoName: '$20 Off Yoga Mats',
    promoType: 'Fixed Amount Off',
    startDate: '2026-01-01',
    endDate: '2026-01-15',
    offerSummary: '$20 discount on all yoga mats',
    buyCondition: 'Any Yoga Mat',
    getOutcome: '$20 Off',
    storeCount: 95,
    hotsheetType: 'Health',
    promoId: 'FIT-YOGA-2026',
    hasError: false,
    errorDetails: null,
  },
  {
    id: 12,
    eventName: 'Pet Supplies Drive',
    promoName: 'Buy 3 Get 1 Pet Food',
    promoType: 'BOGO',
    startDate: '2025-10-01',
    endDate: '2025-10-20',
    offerSummary: 'Buy 3 bags of pet food, get 1 free',
    buyCondition: '3 Bags Pet Food',
    getOutcome: '1 Bag Free',
    storeCount: 140,
    hotsheetType: 'Core',
    promoId: 'PET-FOOD-2025',
    hasError: true,
    errorDetails: {
      title: 'Expired Product Line',
      message: 'This promotion includes products from a discontinued pet food line. Please update the product list.',
      code: 'PRODUCT-LIFECYCLE-002',
      solution: 'Remove discontinued products from the promotion, or select valid replacements.'
    }
  },
  {
    id: 13,
    eventName: 'Outdoor Adventure',
    promoName: '30% Off Camping Gear',
    promoType: 'Percentage Off',
    startDate: '2026-05-01',
    endDate: '2026-05-31',
    offerSummary: '30% discount on all camping equipment',
    buyCondition: 'Any Camping Gear',
    getOutcome: '30% Off',
    storeCount: 75,
    hotsheetType: 'Seasonal',
    promoId: 'OUTDOOR-CAMP-2026',
    hasError: false,
    errorDetails: null,
  },
  {
    id: 14,
    eventName: 'Art & Craft Fair',
    promoName: '$10 Off Craft Kits',
    promoType: 'Fixed Amount Off',
    startDate: '2025-08-10',
    endDate: '2025-08-25',
    offerSummary: '$10 off any craft kit over $50',
    buyCondition: 'Craft Kit > $50',
    getOutcome: '$10 Off',
    storeCount: 55,
    hotsheetType: 'Special',
    promoId: 'ART-CRAFT-2025',
    hasError: false,
    errorDetails: null,
  },
  {
    id: 15,
    eventName: 'DIY Workshop Series',
    promoName: 'Free Admission to Workshops',
    promoType: 'Service Discount',
    startDate: '2025-09-05',
    endDate: '2025-09-20',
    offerSummary: 'Free entry to any DIY workshop with purchase',
    buyCondition: 'Any Purchase',
    getOutcome: 'Free Workshop Entry',
    storeCount: 40,
    hotsheetType: 'Event',
    promoId: 'DIY-WORKSHOP-2025',
    hasError: true,
    errorDetails: {
      title: 'Capacity Limit Exceeded',
      message: 'The number of free admissions exceeds current workshop capacity. Please reduce quantity or specify limited availability.',
      code: 'CAPACITY-LIMIT-001',
      solution: 'Adjust the "Get Outcome" to reflect limited availability or a fixed number of free admissions per store.'
    }
  },
];